---
# Aktivace pluginu, bez kterého by nebylo možné komunikovat se Zabbixem
- name: Enable Zabbix plugin via Grafana API
  ansible.builtin.import_tasks: enable.yml

# Konfigurace propojení na datový zdroj (Zabbix API)
- name: Add Zabbix datasource to Grafana
  ansible.builtin.import_tasks: datasource.yml

# Import hotových vizualizací (JSON soubory)
- name: Add Zabbix-SRV01 dashboard to Grafana
  ansible.builtin.import_tasks: dashboard.yml